version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./database:/app/database
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/database/globalwings.sqlite
